cameras:
  static:
    _target_: spaceman.envs.genesis_env.GenesisSim
    name: static
    fov: 40
    aspect: 1
    nearval: 0.01
    farval: 10
    width: 200
    height: 200
    look_at: !!python/tuple
    - 0
    - 0
    - 0.5
    look_from: !!python/tuple
    - -2.5
    - -3.0
    - 2.5
  gripper:
    _target_: vr_env.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 70
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 84
    height: 84
    look_at:
    - 0.10000000149011612
    - -1.0
    - 0.0
    look_from:
    - 0.07000000029802322
    - 0.10000000149011612
    - -0.10000000149011612
    up_vector:
    - 1.0
    - 0.0
    - 0.0
load_dir: datasets/episode_20260126_163011/
data_path: data
save_dir: null
show_gui: false
processes: 16
max_episode_frames: 694
save_body_infos: true
set_static_cam: false
env:
  cameras: ${cameras}
  show_gui: ${show_gui}
  use_vr: false
scene:
  _target_: vr_env.scene.play_table_scene.PlayTableScene
  _recursive_: false
  name: robot_assisted_docking_scene
  data_path: ${data_path}
  global_scaling: 0.8
  euler_obs: ${robot.euler_obs}
  robot_base_position:
  - -0.34
  - -0.46
  - 0.24
  robot_base_orientation:
  - 0
  - 0
  - 0
  robot_initial_joint_positions:
  - -1.21779206
  - 1.03987646
  - 2.11978261
  - -2.34205014
  - -0.87015947
  - 1.64119353
  - 0.55344866
  surfaces:
    table:
    - - 0.0
      - -0.15
      - 0.46
    - - -0.35
      - -0.03
      - 0.46
    slider_left:
    - - -0.32
      - 0.05
      - 0.46
    - - -0.16
      - 0.12
      - 0.46
    slider_right:
    - - -0.05
      - 0.05
      - 0.46
    - - 0.13
      - 0.12
      - 0.46
  objects:
    movable_objects:
      starlink_satellite:
        file: starlink/urdf/starlink.urdf
        initial_pos: any
        initial_orn: any
      docking_target:
        file: docking_target/urdf/docking_target.urdf
        initial_pos: any
        initial_orn: any
robot:
  _target_: spaceman.robots.satellite_manipulator.SatelliteManipulator
  name: franka_merge
  urdf_path: assets/urdf/franka_merge/urdf/franka_merge.urdf
  euler_obs: true
  gripper_obs: true
  joint_pos_obs: true
  tcp_pos_obs: true
  tcp_quat_obs: true
  base_pos_obs: true
  base_quat_obs: true
  gripper_value_obs: true
episode_metadata:
  episode_id: '20260126_163011'
  num_frames: 694
  action_dim: 7
  robot_obs_dim: 19
  scene_obs_dim: 6
  rgb_static_shape: !!python/tuple
  - 694
  - 200
  - 200
  - 3
  rgb_gripper_shape: !!python/tuple
  - 694
  - 84
  - 84
  - 3
  success: false
  timestamp: '2026-01-26T16:32:13.676399'
